name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        version: [11, 17, 18]
    runs-on: macos-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.version }}

      - run: |
          git clone https://github.com/wordpress-mobile/WordPress-Android.git
          cd WordPress-Android
          git checkout test/fix-unit-tests-execution-above-jdk11
          cp gradle.properties-example gradle.properties
          ./gradlew testWordPressWasabiDebugUnitTest
