name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        version: [11, 17, 18]
        branch: [ "test/fix-unit-tests-execution-above-jdk11", "431c478b1468e9c774650579136cfa050763b48f" ]
    runs-on: macos-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.version }}

      - run: |
          git clone https://github.com/wordpress-mobile/WordPress-Android.git
          cd WordPress-Android
          git checkout ${{ matrix.branch }}
          cp gradle.properties-example gradle.properties
          ./gradlew testWordPressWasabiDebugUnitTest
